### ISSUE TITLE
New live777 stream api

### ISSUE THREAD

**Issue by a-wing** [binbat/live777#164]
- [ ] `--feateures=api`
- [x] POST /api/streams
- [x] GET /api/streams
- [x] GET /api/streams/:id
- [x] DELETE /api/streams

## POST `/stream/:stream`

Create a stream

```json
{
  "audio": ["OPUS"],
  "video": ["VP8", "AV1", "AV1"],
  "dataChannel": ["1", "2", "3"],
  "token": "xxxx"
}
```
`token`: Option, If you want to create a private stream, set this. this `token` equal WHIP POST header auth token
`audio`: Maybe has multiple audio track
`video`: Maybe has multiple video track
`dataChannel`: Maybe has multiple dataChannel, `id` is https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel#id

## DELETE `/stream/:stream`

Delete a stream

* * *

# Auto Create & Delete stream

Need some can config strategy

If Stream don't exist, When WHIP | WHEP request auto create Stream

## Config

in `live777.toml` config

```toml
[strategy.stream]
# When whip request create stream
create_whip = true

# When whep request create stream
create_whep = true

# -1: disable
# 0: immediately delete
# 1~32767: wait (1~32767)s
# When all whip leave
delete_whip = (i16)0
# When all whep leave
delete_whep = (i16)0
```
