### ISSUE TITLE
config parse error

### ISSUE THREAD

**Issue by a-wing** [binbat/live777#77]
```
config parse error: Error { inner: Error { inner: TomlError { message: "missing field `accounts`", original: Some("[auth]\ntokens = [\"live777\"]\n"), keys: ["auth"], span: Some(0..27) } } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

config.toml

```toml
[auth]
tokens = ["live777"]

# [[auth.accounts]]
# username = "live777"
# password = "live777"
```
